# Generated by Django 2.2.4 on 2021-06-06 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_attendance_request_requeststatus_workingdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='requeststatus_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status_foreign', to='registration.RequestStatus'),
        ),
    ]
