# Generated by Django 2.2.4 on 2021-06-06 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_auto_20210606_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='workingdays_attendance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_day', to='registration.WorkingDays'),
        ),
    ]
